/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculationtriangle;

import javax.swing.JOptionPane;

/**
 *
 * @author sevar
 */
public class Triangle extends javax.swing.JFrame {

    /**
     * Creates new form Triangle
     */
    public Triangle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        ladoA1 = new javax.swing.JTextField();
        ladoC1 = new javax.swing.JTextField();
        ladoB1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ladoA1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel1.setText("Area Del Triangulo");

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese los lados del triangulo en centimetros ");

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel3.setText("Lado A:");

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel4.setText("Lado B:");

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel5.setText("Lado C:");

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel6.setText("El triangulo es: ");

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel9.setText("El area  es: ");

        jButton1.setText("Calcular");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(246, 246, 246))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(570, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ladoA1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ladoB1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ladoC1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ladoB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ladoC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ladoA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       
        double ladoA , ladoB, ladoC, angA, angB, angC, A, B, C, anguloA, anguloB, anguloC, P;
        double areaA, areaT, hi, ha,x, y, z, hb, hc, hamEa,hamEaT, hamEbT, hamEb,hamEcT, hamEc;
         try{       
        ladoA = Double.parseDouble(ladoA1.getText());
        ladoB = Double.parseDouble(ladoB1.getText());
        ladoC = Double.parseDouble(ladoC1.getText());
        
        char equi = 0;
        char esc = 0;

        if(ladoA==ladoB && ladoB==ladoC){  
            String eq = "Lado A: "+ladoA + "   Lado B: " + ladoB + "   Lado C: " + ladoC + " Todos sus lados son iguales, Equilatero";
            jLabel7.setText(eq);
            equi = 'E';
        }else{
            if(ladoA==ladoB && ladoA!=ladoC){
                String eq = "Lado A: "+ladoA + "   Lado B: " + ladoB + "   Lado C: " + ladoC + " Tiene dos lados iguales, Isósceles";
                jLabel7.setText(eq);
                equi = 'I';
                esc = 'c';
        }else{
            if(ladoA==ladoC && ladoA!=ladoB){
                String eq = "Lado A: "+ladoA + " Lado B: " + ladoB + " Lado C: " + ladoC + " Tiene dos lados iguales, Isósceles";
                jLabel7.setText(eq);
                equi = 'I'; 
                esc = 'b';
            }else{
                if(ladoB==ladoC && ladoC!=ladoA){
                String eq = "Lado A: "+ladoA + "   Lado B: " + ladoB + "   Lado C: " + ladoC + " Tiene dos lados iguales, Isósceles";
                jLabel7.setText(eq);
                equi = 'E';  
                esc = 'a';
            }else{
                if(ladoA!=ladoB && ladoA!=ladoC && ladoB!=ladoC){
                String eq = "Lado A: "+ladoA + "   Lado B: " + ladoB + "   Lado C: " + ladoC + " Todos los lados son diferentes, Escaleno";
                jLabel7.setText(eq);
                equi = 'S';  
                
                if(ladoA>ladoB && ladoB>ladoC){
                esc = 'd'; 
                }else{
                if(ladoA > ladoC && ladoC > ladoB){
                esc = 'd';
                }else{
                if(ladoB > ladoA && ladoA > ladoC){
                esc = 'e';
                }else{
                if(ladoB > ladoC && ladoC > ladoA){
                esc = 'e';
                }else{
                if(ladoC > ladoA && ladoA > ladoB){
                esc = 'f';
                }else{
                if(ladoC > ladoB && ladoB > ladoA){
                esc = 'f'; 
                }
                    }
                        }
                            }
                                }
                                    }
                                        }
                                            }
            }
            }
        }


        switch (equi){
            case 'E':
                areaA = (Math.sqrt(3)/4)*Math.pow(ladoA, 2);
                String AreaE = "Area "+areaA + " cm";
                jLabel10.setText(AreaE);
                hi = (Math.sqrt(3)/2)*ladoA;
                JOptionPane.showMessageDialog(null, "Angulo: " + hi);
                break;
            case 'I':
                anguloA = ((ladoA * ladoA) - (ladoB * ladoB) - (ladoC *ladoC))/(-2*ladoB*ladoC); //ley del coseno
                anguloB = (Math.pow(ladoB,2)-Math.pow(ladoA, 2)-Math.pow(ladoC, 2))/(-2*ladoA*ladoC);
                anguloC = (Math.pow(ladoC,2)-Math.pow(ladoA, 2)-Math.pow(ladoB, 2))/(-2*ladoB*ladoA);
                A=Math.acos(anguloA);
                angA = Math.toDegrees(A);
                B=Math.acos(anguloB);
                angB = Math.toDegrees(B);
                C=Math.acos(anguloC);
                angC = Math.toDegrees(C);
                JOptionPane.showMessageDialog(null, "Angulo A: " + angA + "  \nAngulo B: " + angB + "  \nAngulo C: " + angC );
                P=(ladoA+ladoB+ladoC)/2;
                areaA = (P*(P-ladoA)*(P-ladoB)*(P-ladoC));
                areaT = Math.sqrt(areaA);
                String Area = "Area: " + areaT + " cm";
                jLabel10.setText(Area);
                break;
                
            case 'S':
                anguloA = ((ladoA * ladoA) - (ladoB * ladoB) - (ladoC *ladoC))/(-2*ladoB*ladoC); //ley del coseno
                anguloB = (Math.pow(ladoB,2)-Math.pow(ladoA, 2)-Math.pow(ladoC, 2))/(-2*ladoA*ladoC);
                anguloC = (Math.pow(ladoC,2)-Math.pow(ladoA, 2)-Math.pow(ladoB, 2))/(-2*ladoB*ladoA);
                A=Math.acos(anguloA);
                angA = Math.toDegrees(A);
                B=Math.acos(anguloB);
                angB = Math.toDegrees(B);
                C=Math.acos(anguloC);
                angC = Math.toDegrees(C);
                JOptionPane.showMessageDialog(null, "Angulo A: " + angA + "  \nAngulo B: " + angB + "  \nAngulo C: " + angC );
                P=(ladoA+ladoB+ladoC)/2;
                areaA = (P*(P-ladoA)*(P-ladoB)*(P-ladoC));
                areaT = Math.sqrt(areaA);
                String Areae = "Area: " + areaT + " cm";
                jLabel10.setText(Areae);
                break;
        }
        switch (esc){
            case 'a':
                x = Math.pow(ladoB, 2) - (Math.pow(ladoA, 2))/4;
                ha = Math.sqrt(x);
                String vc = "Area: " + ha + " cm";
                jLabel10.setText(vc);
                break;
                
            case 'b':
                y = Math.pow(ladoA, 2) - (Math.pow(ladoB, 2))/4;
                hb = Math.sqrt(y);
                String vb = "Area: " + hb + " cm";
                jLabel10.setText(vb);
                break;  
                
            case 'c':
                z = Math.pow(ladoB, 2) - (Math.pow(ladoC, 2))/4;
                hc = Math.sqrt(z);
                String va = "Area: " + hc + " cm";
                jLabel10.setText(va);
                break;  
            case 'd':
                P = (ladoA+ladoB+ladoC)/2;
                hamEa = (P*(P-ladoA)*(P-ladoB)*(P-ladoC));
                hamEaT = (2/ladoA)*Math.sqrt(hamEa);
                
                String Ea = "Angulo: "+ hamEaT + "  cm";
                jLabel10.setText(Ea);
                break;
            case 'e':
                P = (ladoA+ladoB+ladoC)/2;
                hamEb = (P*(P-ladoA)*(P-ladoB)*(P-ladoC));
                hamEbT = (2/ladoB)*Math.sqrt(hamEb);
                
                String Eb = "Angulo: "+ hamEbT + "  cm";
                jLabel10.setText(Eb);
                break; 
            case 'f':
                P = (ladoA+ladoB+ladoC)/2;
                hamEc = (P*(P-ladoA)*(P-ladoB)*(P-ladoC));
                hamEcT = (2/ladoC)*Math.sqrt(hamEc);
                
                String Ec = "Angulo: "+ hamEcT + "  cm";
                jLabel10.setText(Ec);
                break;
        }
        }catch(Exception e){
        System.out.print("Diferencia muy alta");
        }
    }//GEN-LAST:event_jButton1MouseClicked


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Triangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Triangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Triangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Triangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Triangle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField ladoA1;
    private javax.swing.JTextField ladoB1;
    private javax.swing.JTextField ladoC1;
    // End of variables declaration//GEN-END:variables
}
